// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ReactorTodayContainer
{
	public partial class EventCell : UITableViewCell
	{
		public EventCell (IntPtr handle) : base (handle)
		{
		}

        public string Title 
        {
            get
            {
                return titleLabel.Text;
            }
            set
            {
                titleLabel.Text = value;
            }
        }

        public string Description
        {
            get
            {
                return descriptionLabel.Text;
            }
            set
            {
                descriptionLabel.Text = value;
            }
        }

        public string StartTime 
        {
            get
            {
                return startTimeLabel.Text;
            }
            set
            {
                startTimeLabel.Text = $"Starts @ {value}";
            }
        }

        public string EndTime
        {
            get
            {
                return endTimeLabel.Text;
            }
            set
            {
                endTimeLabel.Text = $"Ends @ {value}";
            }
        }

        public string Location
        {
            get
            {
                return locationLabel.Text;
            }
            set
            {
                locationLabel.Text = value;
            }
        }
    }
}
