// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ReactorTodayContainer
{
	public partial class EventTableViewCell : UITableViewCell
	{
		public EventTableViewCell (IntPtr handle) : base (handle)
		{
		}

        public string Title 
        {
            get
            {
                return lblTitle.Text;
            }
            set
            {
                lblTitle.Text = value;
            }
        }

        public string Description 
        {
            get
            {
                return lblDescription.Text;
            }
            set
            {
                lblDescription.Text = value;
            }
        }

        public string Location
        {
            get
            {
                return lblLocation.Text;
            }
            set
            {
                lblLocation.Text = value;
            }
        }

        public string StartTime
        {
            get
            {
                return lblStartTime.Text;
            }
            set
            {
                lblStartTime.Text = $"Starts @ {value}";
            }
        }
	}
}
