// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ReactorTodayContainer
{
	public partial class HeaderCell : UITableViewCell
	{
		public HeaderCell (IntPtr handle) : base (handle)
		{
		}
	}
}
